
name: Global Build Numbers

on: [push]

permissions:
  contents: read

jobs:
  testBuildNumbers:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macOS-10.14, windows-2016, windows-latest, ubuntu-18.04, ubuntu-latest]
        os: [windows-latest, ubuntu-latest]
    # runs-on: windows-latest
    steps:
      - name: install aws cli
        uses: ohthepain/action-install-aws-cli@v1.0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'
      # All commands after this point have access to the AWS CLI
      # - name: "test s3 permissions"
      #   # All commands after this point have access to the AWS CLI
      #   run: aws s3 ls
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: 'eu-central-1'
      # - name: Check DynamoDB Permissions
      #   run: aws dynamodb list-tables
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: 'eu-central-1'

      - name: Set version number to 77
        uses: ohthepain/global-build-numbers@main
        with:
          DYNAMO_TABLE_NAME: 'build-numbers'
          DYNAMO_PARTITION_KEY: 'product-id'
          PRODUCT_ID: 'game-config'
          OPERATION: 'set'
          VALUE: 77
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'

      - name: Increment version number
        uses: ohthepain/global-build-numbers@main
        id: inc-ver-num
        with:
          DYNAMO_TABLE_NAME: 'build-numbers'
          DYNAMO_PARTITION_KEY: 'product-id'
          PRODUCT_ID: 'game-config'
          OPERATION: 'increment'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'

      - name: Version number should be 78
        run: echo ${{ steps.inc-ver-num.outputs.result }}
    